title = "BSAI Secret Detection Configuration"

[[rules]]
id = "anthropic-api-key"
description = "Anthropic API Key"
regex = '''sk-ant-[a-zA-Z0-9\-_]{95,}'''
keywords = ["sk-ant"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}'''
keywords = ["sk-"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
keywords = ["AKIA"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA )?PRIVATE KEY-----'''
keywords = ["BEGIN PRIVATE KEY", "BEGIN RSA PRIVATE KEY"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''[a-zA-Z0-9_-]*[Kk][Ee][Yy][a-zA-Z0-9_-]*[:][ ]*['"][a-zA-Z0-9_\-]{20,}['"]'''
keywords = ["key", "api", "token"]

[[rules]]
id = "password"
description = "Password in configuration"
regex = '''[a-zA-Z0-9_-]*[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd][a-zA-Z0-9_-]*[:][ ]*['"][a-zA-Z0-9_\-!@#$%^&*()]{8,}['"]'''
keywords = ["password", "passwd", "pwd"]

[allowlist]
description = "Allowlist for false positives"
files = [
    '''\.env\.example$''',
    '''\.env\.template$''',
    '''README\.md$''',
    '''docs/.*\.md$''',
    '''tests/fixtures/.*''',
]

regexes = [
    '''your_.*_key_here''',
    '''replace_with_actual''',
    '''example_.*''',
    '''demo_.*''',
    '''test_.*_key''',
    '''sk-ant-example.*''',
    '''AKIA[0-9A-Z]{4}EXAMPLE''',
]