"""Pydantic schemas for API request/response validation."""

from .memory import (
    ConsolidateResult,
    DecayResult,
    MemoryDetailResponse,
    MemoryResponse,
    MemorySearchRequest,
    MemorySearchResult,
    MemoryStatsResponse,
)
from .requests import (
    BulkSessionAction,
    QAConfigRequest,
    SessionCreate,
    SnapshotCreate,
    TaskCreate,
    TaskReject,
    TaskResume,
)
from .responses import (
    ActionResponse,
    AgentStepResponse,
    ArtifactResponse,
    BuildResultResponse,
    EpicProgress,
    ErrorResponse,
    FeatureProgress,
    LintResultResponse,
    MilestoneDetailResponse,
    MilestoneResponse,
    PaginatedResponse,
    ProgressResponse,
    QAResultResponse,
    SessionDetailResponse,
    SessionResponse,
    SnapshotResponse,
    TaskDetailResponse,
    TaskResponse,
    TestResultResponse,
    TypecheckResultResponse,
)
from .websocket import (
    BreakpointCurrentState,
    BreakpointHitPayload,
    LLMChunkPayload,
    LLMCompletePayload,
    MilestoneProgressPayload,
    PreviousMilestoneInfo,
    TaskCompletedPayload,
    TaskFailedPayload,
    TaskProgressPayload,
    TaskStartedPayload,
    WSMessage,
    WSMessageType,
)

__all__ = [
    # Requests
    "SessionCreate",
    "TaskCreate",
    "TaskResume",
    "TaskReject",
    "SnapshotCreate",
    "BulkSessionAction",
    "QAConfigRequest",
    # Responses
    "ActionResponse",
    "AgentStepResponse",
    "SessionResponse",
    "SessionDetailResponse",
    "TaskResponse",
    "TaskDetailResponse",
    "MilestoneResponse",
    "MilestoneDetailResponse",
    "SnapshotResponse",
    "ArtifactResponse",
    "PaginatedResponse",
    "ProgressResponse",
    "FeatureProgress",
    "EpicProgress",
    "ErrorResponse",
    # QA Results
    "QAResultResponse",
    "LintResultResponse",
    "TypecheckResultResponse",
    "TestResultResponse",
    "BuildResultResponse",
    # Memory
    "MemoryResponse",
    "MemoryDetailResponse",
    "MemorySearchResult",
    "MemorySearchRequest",
    "ConsolidateResult",
    "DecayResult",
    "MemoryStatsResponse",
    # WebSocket
    "WSMessageType",
    "WSMessage",
    "TaskStartedPayload",
    "TaskProgressPayload",
    "TaskCompletedPayload",
    "TaskFailedPayload",
    "MilestoneProgressPayload",
    "PreviousMilestoneInfo",
    "LLMChunkPayload",
    "LLMCompletePayload",
    "BreakpointCurrentState",
    "BreakpointHitPayload",
]
