global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bsai-dev'
    environment: 'development'

scrape_configs:
  # BSAI Application
  - job_name: 'bsai-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL (if postgres_exporter is added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis (if redis_exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
