"""Generated prompt model."""

from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from sqlalchemy import INTEGER, TEXT, VARCHAR, ForeignKey, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base

if TYPE_CHECKING:
    from .milestone import Milestone
    from .system_prompt import SystemPrompt


class GeneratedPrompt(Base):
    """Meta Prompter outputs for Worker agent optimization.

    Attributes:
        id: Primary key (UUID)
        milestone_id: Foreign key to milestones table
        system_prompt_id: Optional foreign key to system_prompts table
        generated_content: Optimized prompt generated by Meta Prompter
        strategy_used: Prompt engineering strategy applied
        model_used: LLM model used for generation
        token_count: Total tokens used
        created_at: Creation timestamp
    """

    __tablename__ = "generated_prompts"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    milestone_id: Mapped[UUID] = mapped_column(ForeignKey("milestones.id"), index=True)
    system_prompt_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("system_prompts.id"), index=True, nullable=True
    )
    generated_content: Mapped[str] = mapped_column(TEXT)
    strategy_used: Mapped[str] = mapped_column(VARCHAR(50), default="")
    model_used: Mapped[str] = mapped_column(VARCHAR(100), default="")
    token_count: Mapped[int] = mapped_column(INTEGER, default=0)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    # Relationships
    milestone: Mapped["Milestone"] = relationship(back_populates="generated_prompts")
    system_prompt: Mapped["SystemPrompt"] = relationship(back_populates="generated_prompts")

    def __repr__(self) -> str:
        return f"<GeneratedPrompt(id={self.id}, milestone_id={self.milestone_id})>"
