"""Generated prompt model."""

from datetime import datetime
from typing import TYPE_CHECKING, Any
from uuid import UUID, uuid4

from sqlalchemy import TEXT, VARCHAR, ForeignKey, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base

if TYPE_CHECKING:
    from .milestone import Milestone
    from .prompt_usage_history import PromptUsageHistory


class GeneratedPrompt(Base):
    """Meta Prompter outputs for Worker agent optimization.

    Attributes:
        id: Primary key (UUID)
        milestone_id: Foreign key to milestones table
        meta_prompter_model: LLM model used by Meta Prompter
        original_request: Original task request
        task_context: Additional context provided
        generated_prompt: Optimized prompt generated by Meta Prompter
        prompt_strategy: Strategy metadata (JSON)
        created_at: Creation timestamp
    """

    __tablename__ = "generated_prompts"

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    milestone_id: Mapped[UUID] = mapped_column(ForeignKey("milestones.id"), index=True)
    meta_prompter_model: Mapped[str | None] = mapped_column(VARCHAR(100))
    original_request: Mapped[str | None] = mapped_column(TEXT)
    task_context: Mapped[str | None] = mapped_column(TEXT)
    generated_prompt: Mapped[str] = mapped_column(TEXT)
    prompt_strategy: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    # Relationships
    milestone: Mapped["Milestone"] = relationship(back_populates="generated_prompts")
    prompt_usage_history: Mapped[list["PromptUsageHistory"]] = relationship(
        back_populates="generated_prompt", lazy="selectin"
    )

    def __repr__(self) -> str:
        return f"<GeneratedPrompt(id={self.id}, milestone_id={self.milestone_id})>"
