"""Update generated_prompts add strategy model token fields

Revision ID: ee8e2ece8955
Revises: 05964df676b8
Create Date: 2025-12-30 09:51:54.280927

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee8e2ece8955"
down_revision: str | Sequence[str] | None = "05964df676b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_prompts",
        sa.Column("strategy_used", sa.VARCHAR(length=50), nullable=False, server_default=""),
    )
    op.add_column(
        "generated_prompts",
        sa.Column("model_used", sa.VARCHAR(length=100), nullable=False, server_default=""),
    )
    op.add_column(
        "generated_prompts",
        sa.Column("token_count", sa.INTEGER(), nullable=False, server_default="0"),
    )
    op.alter_column("generated_prompts", "system_prompt_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "generated_prompts", "system_prompt_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("generated_prompts", "token_count")
    op.drop_column("generated_prompts", "model_used")
    op.drop_column("generated_prompts", "strategy_used")
    # ### end Alembic commands ###
