"""Add description and acceptance_criteria to milestones

Revision ID: 05964df676b8
Revises: 20251226_0945
Create Date: 2025-12-30 09:04:13.702726

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05964df676b8"
down_revision: str | Sequence[str] | None = "20251226_0945"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "custom_llm_models",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "custom_llm_models",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("custom_llm_models_name_key"), "custom_llm_models", type_="unique")
    op.drop_index(op.f("ix_custom_llm_models_name"), table_name="custom_llm_models")
    op.create_index(op.f("ix_custom_llm_models_name"), "custom_llm_models", ["name"], unique=True)
    op.add_column(
        "milestones", sa.Column("description", sa.TEXT(), nullable=False, server_default="")
    )
    op.add_column(
        "milestones", sa.Column("acceptance_criteria", sa.TEXT(), nullable=False, server_default="")
    )
    op.drop_constraint(op.f("user_settings_user_id_key"), "user_settings", type_="unique")
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.create_index(op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.create_index(op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=False)
    op.create_unique_constraint(
        op.f("user_settings_user_id_key"),
        "user_settings",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("milestones", "acceptance_criteria")
    op.drop_column("milestones", "description")
    op.drop_index(op.f("ix_custom_llm_models_name"), table_name="custom_llm_models")
    op.create_index(op.f("ix_custom_llm_models_name"), "custom_llm_models", ["name"], unique=False)
    op.create_unique_constraint(
        op.f("custom_llm_models_name_key"),
        "custom_llm_models",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "custom_llm_models",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "custom_llm_models",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
